name: Run Tests

on:
  push:
    branches:
      - main
jobs:
  test:
    name: Run Jest Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check Repository
        uses: actions/checkout/@v5

      - name: Download Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "22"

      - name: Install Dependencies
        run: npm install

      - name: Run Jest
        run: npm run test
        env:
          CI: true
